### ISSUE TITLE
Dx can't dex 1.5

### ISSUE THREAD

**Issue by ZacSweers** [JakeWharton/AutoValueAnnotations#6]
Seeing this when trying to use it, not sure if this is something anyone else has seen

```
Caused by: com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:476)
	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
	at com.android.dx.command.dexer.Main.parseClass(Main.java:792)
	at com.android.dx.command.dexer.Main.access$1600(Main.java:91)
	at com.android.dx.command.dexer.Main$ClassParserTask.call(Main.java:1727)
	at com.android.dx.command.dexer.Main.processClass(Main.java:778)
	... 24 more
1 error; aborting
```

**Comment by JakeWharton** [comment]
This library is just a repackaging of the auto value classes. Those are the ones built targeting Java 8. If your toolchain can't process them (i.e., not using desugar) then you need to file an issue onto https://github.com/google/auto/.
